/**
 * Exports the objects generated by each file in the err directory
 * @module err
 */

/**
 * The error object generated by the {@link module:err/account} module and used by the
 * {@link module:models/account|models/account} module.
 * @type {AccountErrors}
 */
exports.account = require('./account');